### PR TITLE
Run CI on Python 3.11

### PR DESCRIPTION
**Pull request by PerchunPak**

### CODE REVIEW

**Review by ItsDrike — APPROVED** [review]
It might be worth it to only run CI on the highest and lowest supported versions, to avoid having to run a ton of checks with little benefit. Especially since GitHub limits the amount of actions we can run concurrently within the organization.

However that should probably be discussed in another issue, this alone looks good to be merged.

**Comment by PerchunPak** [comment]
How about add Python 3.12 to CI? And rename this and add badge "We're supporting 3.11 and 3.12" [here](https://github.com/py-mine/mcstatus/blob/21c6d04eb663c3b68d8effab6489b21dfa829850/pyproject.toml#L15-L19)? Or I should separate this change, as it's unrelated to CI?

**Comment by kevinkjt2000** [comment]
I'd only put 3.11 there. 3.12 will probably come out in October 2023.

**Comment by PerchunPak** [comment]
It's always better to be prepared before future updates.

**Comment by ItsDrike** [comment]
> It's always better to be prepared before future updates.

Sure, but putting a version of python that isn't expected to be out for another year simply isn't necessary. In fact, it'd probably just be confusing to the people looking at that badge, causing potential issue reports on it being a typo or even wrongly convincing someone that 3.12 is already out and they've somehow missed it. Just putting 3.11 will do fine.

**Comment by PerchunPak** [comment]
Fine, as I understand this touches to classifier in `pyproject.toml`, so what about CI? (it will be displayed as `3.12-dev`, so people (I hope) will not be confused)

**Comment by ItsDrike** [comment]
I think we should try to be limiting the amount of CI checks we're doing. If there's little to no benefit in adding a new check, it certainly shouldn't be here.

GitHub organizations have a limited amount of workflows that can be run in them concurrently. This is already affecting us with newly pushed commits, as we need to wait for some of the checks to finish until the rest even starts, slowing the checks down.

I don't believe that having running tests for python 3.12 is a check worth adding, especially since it'd actually mean 3 additional workflows (win, mac, linux). This check wouldn't give us almost any benefit, as pretty much nobody is gonna be using mcstatus in the current builds of 3.12, hardly anyone is using mcstatus with 3.11

This would be a different story if this was concerning a new python version that's already in the release-candidate phase, at which point library developers are actually advised to run checks against these versions to catch potential bugs, and prepare for the full release, ensuring there weren't any deprecations/removals which we utilize, but 3.12 is far from being in this stage.

Another major reason against adding 3.12 to the CI checks is that this version isn't stable. It could easily include bugs and issues as it's still in development, and we wouldn't want the checks failing on someone's commits just because of a bug in python 3.12 itself.

**Comment by PerchunPak** [comment]
:+1:, you can merge it.

**Pull request merged**
