### PR TITLE
Use `time.perf_counter` for latency

### LINKED ISSUE #316: OSError: Received invalid status response packet
I have problems with ping some servers. List of examples: 
1. `82.162.60.67:37821` (but: [mcsrvstat.us](https://mcsrvstat.us/server/82.162.60.67:37821))
2. `sr4.fuix.net:10002` (but: [mcsrvstat.us](https://mcsrvstat.us/server/sr4.fuix.net:10002))
3. `88.198.55.217:25565` (but: [mcsrvstat.us](https://mcsrvstat.us/server/88.198.55.217:25565))
4. `moscow.gamai.ru:41001` (but: [mcsrvstat.us](https://mcsrvstat.us/server/moscow.gamai.ru:41001))

> File "/usr/local/lib/python3.9/site-packages/mcstatus/pinger.py", line 69, in read_status raise IOError("Received invalid status response packet.")
> OSError: Received invalid status response packet.

### PR DESCRIPTION
**Pull request by PerchunPak**
Fixes #316.

### CODE REVIEW

**Comment by PerchunPak** [comment]
I do not know how to fix such low level tests, because I really weak in low level.

**Review by kevinkjt2000 — APPROVED** [review]

**Review by kevinkjt2000 — CHANGES_REQUESTED** [review]
Good idea. Now, the tests need to reflect the new data.

**Comment by PerchunPak** [comment]
I know, but how? I'm too bad in such low level things and I completely don't understand what tests do.

**Review by ItsDrike — COMMENTED** [review]
Ok so, after some investigation, the issue that you see in the tests occurs because you've edited the `_retry_status` (and `_retry_async_status` in a way that now no longer performs the `test_ping` call. 

However the tests expect this call to be performed, and we test the mocked socket for presence of certain data, corresponding to us sending a [Ping packet](https://wiki.vg/Protocol#Ping_Request), which now doesn't happen, hence the failure.

If you'll be removing this additional data, make sure to also remove the read data the mocked socket holds, representing the response to our Ping packet (being the [Pong packet](https://wiki.vg/Protocol#Ping_Response)).

**Review by kevinkjt2000 — APPROVED** [review]

**Pull request merged**
