### PR TITLE
Fix Bedrock PocketMine Servers Query

### PR DESCRIPTION
**Pull request by AlphaBaqpla**
I change magick packet to compile with RakLib

### CODE REVIEW

**Comment by kartashovio** [comment]
We talked to @AlphaBaqpla . He informed me that this fixes the issue #433

**Comment by PerchunPak** [comment]
Could you please give any reference why did you change the packet exactly in this way? Also, tests seems like going to fail with this kind of changes, check them please.

**Comment by AlphaBaqpla** [comment]
> Не могли бы вы дать какую-либо справку, почему вы изменили пакет именно таким образом? Кроме того, тесты, похоже, потерпят неудачу с такого рода изменениями, проверьте их, пожалуйста.

RakNet send it
https://github.com/facebookarchive/RakNet/blob/1a169895a900c9fc4841c556e16514182b75faf8/Source/RakPeer.cpp#L135

**Comment by AlphaBaqpla** [comment]
I double-checked everything and fixed the error due to which the validation test did not pass

**Pull request closed without merging**
