### PR TITLE
Use `TypedDict` to avoid all the type casts in status raw response

### PR DESCRIPTION
**Pull request by PerchunPak**

### CODE REVIEW

**Review by ItsDrike — CHANGES_REQUESTED** [review]
I'm not a huge fan of defining these TypedDicts in `if TYPE_CHECKING` block, but it is currently indeed necessary as they're 3.8+, and mcstatus still supports 3.7. 

However doing this then leads to using type ignores when actually passing these dicts (although we could also use casts like `cast("RawResponsePlayer", {name="foo", id="bar"})`, which I would personally prefer). Considering the goal of this PR is to avoid type needing casts, this isn't ideal.

The way we would normally do this is to create instances of typed dicts directly, like: `RawResponsePlayer(name="foo", id="bar")`, which gives us `dict` objects on runtime, but obviously this is impossible considering we can't use these classes on runtime.

But there is a way to get around this nicely, and still essentially allow creation of these typed dicts on runtime, avoiding the need for casting (or type-ignores) completely. To do this, we can use logic like this:
```py
if TYPE_CHECKING:
    class Foo(TypedDict):
        ...
else:
    Foo = dict
    
x = Foo(...)
assert type(x) is dict  # x is simply a dict on runtime (same as initializing a typed-dict in 3.8)
typing_extensions.reveal_type(x)  # x is of type Foo (TypedDict) - evaluated only at typing-time
```

That said, I also wouldn't necessarily be completely against simply dropping 3.7 entirely, as most distributions don't ship it anymore (certainly not the bigger ones) and it is fairly outdated by now (it was released in 2018, and is already in only security fix phase, meaning no more bugs will be fixed and only major security issues will be addressed. The final end-of-life for 3.7 is still relatively far off though - 2023-06, more in [PEP 537](https://peps.python.org/pep-0537/)). But obviously, this would require another PR.

**Comment by PerchunPak** [comment]
> I'm not a huge fan of defining these TypedDicts in `if TYPE_CHECKING` block

They are there also because `typing.Required` and `typing.NotRequired` will appear only in Python 3.11 ([PEP 655](https://peps.python.org/pep-0655/)).

> However doing this then leads to using type ignores when actually passing these dicts

No. Type checker perfectly works without direct access to these `TypedDict`s. All type ignores that was added here, was because those tests tested function when passed dict is invalid (which is actually triggered type checker).

**Comment by ItsDrike** [comment]
> They are there also because typing.Required and typing.NotRequired will appear only in Python 3.11 ([PEP 655](https://peps.python.org/pep-0655/)).

`__future__.annotations` covers that already, it's just a type-hint, there's no need to have it in `if TYPE_CHECKING`. Well there is, but it's only because `TypedDict` itself is 3.8+, not because of the 3.11+ Required/NotRequired, and if python 3.7 got dropped, we would be able to move this outside of this if block.

> No. Type checker perfectly works without direct access to these TypedDicts.

I'm not saying the type-checker is failing here, all I'm saying is that doing `x = {"name": "foo", "id": "bar"}` will **not** result in `x` being of `RawResponsePlayer` TypedDict, it will only get inferred as `dict`, and when it's later passed around into something that requires `RawResponsePlayer`, type-checker will report that as a failure, it won't go back to the definition to check if it isn't by a chance actually matching this TypedDict. This is why initialization using the TypedDict class directly is always preferred. Here's a more detailed example that demonstrates this:

image

**Comment by PerchunPak** [comment]
So how about use `x: Foo = {...}`?

**Comment by ItsDrike** [comment]
> So how about use `x: Foo = {...}`?

This is essentially the same as my last example in the image, where we pass a dict directly and pyright only knows it's `Foo` because it expects it. But if we get a dict dynamically by generating it somehow, pyright can't infer it, and doing something like `x: Foo = dict(x=2, y=4)` will fail. However doing `x = Foo(**a)` for example would work just fine without any casting or type ignoring.

**Comment by PerchunPak** [comment]
Zero errors from pyright:
```py
from typing_extensions import TypedDict, reveal_type

class Foo(TypedDict):
    x: int
    y: int

x: Foo = {"x": 2, "y": 4}
reveal_type(x)  # Type of "x" is "Foo"

def my_func(y: Foo):
    ...

my_func(x)
```

**Comment by PerchunPak** [comment]
(Also these `TypeDict`s are not public, they used only inside one file and will not be used anywhere else)

**Comment by ItsDrike** [comment]
> Zero errors from pyright:
> 
> ```python
> from typing_extensions import TypedDict, reveal_type
> 
> class Foo(TypedDict):
>     x: int
>     y: int
> 
> x: Foo = {"x": 2, "y": 4}
> reveal_type(x)  # Type of "x" is "Foo"
> 
> def my_func(y: Foo):
>     ...
> 
> my_func(x)
> ```

I'm aware.. that wasn't my point...

Consider this:
```py
x = generate_dict_somehow()  # gives dict[str, int]
y: Foo = x  # error

# Since `generate_dict_somehow` only has `dict[str, int]` as return annotation even doing
x: Foo = generate_dict_somehow()
# Would be failing. That's the point I was making... As I've said, I'm quite aware that doing `x: Foo = {...}` works,
# pyright just explicitly infers that because it knows to, and the dict was specified explicitly
# but we won't necessarily have the luxury of specifying the dict explicitly every time we'll need to use this
# and we might need to do things like modifying the dict at some point like:
x: Foo = {"x": 1}  # We can't yet define y (for whatever reason that may come up), leading to a failure here
x["y"] = 5
b: Foo = x  # This won't work either, since pyright no longer knows the complete dict structure at this point
```

**Comment by PerchunPak** [comment]
I understood. But anyway, why is this have any weight here? These `TypedDict`s are used only here, and will not be used anywhere else.

**Comment by ItsDrike** [comment]
> I understood. But anyway, why is this have any weight here? These `TypedDict`s are used only here, and will not be used anywhere else.

It will allow us to remove type ignores in tests, and it makes things easier in the future, we don't know how this code may change in the future, and there's no reason not to do things properly here, if we can.

**Comment by PerchunPak** [comment]
> It will allow us to remove type ignores in tests

It will not, those type ignores are because they passing invalid dicts, and this is the idea of these tests.

> there's no reason not to do things properly here, if we can

However we can't now. Only if block this PR by the PR which removing support of 3.7, but should second one replace such things?

We can add mark to #388 to also move these `TypedDict`s out of `if TYPE_CHECKING` block.

**Comment by ItsDrike** [comment]
> However we can't now. Only if block this PR by the PR which removing support of 3.7, but should second one replace such things?

As I explained in the example on my first review post, we can, by doing `Foo = dict` in `else` block to `if TYPE_CHECKING`.

**Review by ItsDrike — APPROVED** [review]

**Comment by PerchunPak** [comment]
What are this waiting for? @kevinkjt2000?

**Comment by ItsDrike** [comment]
Yes and no, I do sometimes like to leave approved PRs wait around for it bit, because it does give others (not necessarily just kevin) a time to submit their reviews. There may be someone who realizes something I haven't which might fix some bug before the PR makes it's way to master, and potentially introduces a bug into a release.

If no one submits another review within some reasonable time, I will merge the PR eventually, but I find it a good practice to leave PRs like this. Even though there isn't necessarily that much that could go wrong with this specific PR, I still think it's valuable to wait with these not even a day old PRs, so that everyone interested can get a chance to see what's being introduced without missing it.

**Review by kevinkjt2000 — APPROVED** [review]

**Pull request merged**
