### PR TITLE
Add docstrings and seperate things. Closes #210

### LINKED ISSUE #210: Synchronous operations inside async functions
> [ba1dr](https://github.com/ba1dr) **Authored by [ba1dr](https://github.com/ba1dr)**
_<time datetime="2022-02-13T17:59:22Z" title="Sunday, February 13th 2022, 11:59:22 am -06:00">Feb 13, 2022</time>_

---

mcstatus==8.0.0

I have a hanging process while I query servers in async mode. This happens not always - 1-2 times a day.
I managed to reproduce this only after 3 hours in infinite loop of polling 100+ servers.
See stacktrace below.

```
...
  File "/opt/myfolder/some_file.py", line 145, in async_query
    return await mcserver.async_query(tries=2)
  File "/usr/local/lib/python3.9/dist-packages/mcstatus/server.py", line 193, in async_query
    await querier.handshake()
  File "/usr/local/lib/python3.9/dist-packages/mcstatus/querier.py", line 70, in handshake
    self.challenge = int(packet.read_ascii())
  File "/usr/local/lib/python3.9/dist-packages/mcstatus/protocol/connection.py", line 80, in read_ascii
    result.extend(self.read(1))
KeyboardInterrupt
```

As I can see there are lots of synchronous operations in functions defined as `async`.

```
...
class AsyncServerQuerier(ServerQuerier):
    async def _read_packet(self):
        packet = Connection()
...

    async def handshake(self):
        await self.connection.write(self._create_handshake_packet())

        packet = await self._read_packet()
        self.challenge = int(packet.read_ascii())

...
```

here `read_ascii()` is a sync operation.

Next: `QueryResponse.from_connection()` is sync too.

And so on..

### LINKED ISSUE #214: UDPAsyncSocketConnection cannot write anything special itself
> [CoolCat467](https://github.com/CoolCat467) **Authored by [CoolCat467](https://github.com/CoolCat467)**
_<time datetime="2022-02-14T00:02:52Z" title="Sunday, February 13th 2022, 6:02:52 pm -06:00">Feb 13, 2022</time>_

---

`UDPAsyncSocketConnection`'s definition of `write` is an asynchronous function, while it's base class `AsyncReadConnection`'s base class `Connection` expects `write` to be a synchronous function for all of the special write functions like `write_utf`. This appears to have never been detected because everything that uses `UDPAsyncSocketConnection` manually writes everything.

### PR DESCRIPTION
**Pull request by CoolCat467**
Bit of a big change to be honest. This is something I've been working on for a while really. Adds doc strings to pretty much everything, adds slots to all the classes, separates Connection into `BaseConnection`, `BaseReadSync`, and `BaseWriteSync` (don't worry `Connection` is still there, just subclasses all of these.) so that there can be separate `BaseReadAsync` and `BaseWriteAsync`, so that `TCPAsyncSocketConnection` and `UDPAsyncSocketConnection` can exist and not have tons of duplicated code.

Also adds unused `read_varlong` and `write_varlong` functions, this could be removed but why not.

This might make python 3.7 not work right because I got rid of some odd stuff with the `BytesConvertable` type, but I haven't tested.

### CODE REVIEW

**Comment by ItsDrike** [comment]
Thanks! However we've [made the decision](https://discord.com/channels/936788458939224094/936788458939224097/945315223718494248) to slowly move away from our custom `Connection` implementation in favor of using [PyMine-Net](https://github.com/py-mine/PyMine-Net/) as a library which will handle these low-level things for us, since this repo isn't really a place to maintain these. For this reason, any big non-critical changes to how it works are probably not worth making considering the whole file will be removed completely at some point.

**Comment by CoolCat467** [comment]
What do you mean in the "made the decision" link? It doesn't go anywhere.

**Comment by ItsDrike** [comment]
> What do you mean in the "made the decision" link? It doesn't go anywhere.

It's a link to our discord server, though you have to join it to be able to access the link. You can join it by clicking on the discord badge in our README, or by finding it in a pinned issue (Community Chat)

**Comment by kevinkjt2000** [comment]
I'm not opposed to having improvements to these connections in the meanwhile. A shift to using pymine-net is a change that'll probably take a while and it hasn't even started yet.

**Review by kevinkjt2000 — CHANGES_REQUESTED** [review]
Apologies for getting around to reviewing this a bit late, and now there are a few conflicts to fix before this can be reviewed. Also, it seems that some tests failed too. Please update the code with a rebase or merge of the latest from master and then we can start to debug the broken tests.

**Comment by CoolCat467** [comment]
Rebased in #273

**Pull request closed without merging**
