### PR TITLE
Rename `status_response` to `responses`

### PR DESCRIPTION
**Pull request by PerchunPak**
As we have #682, I thought it would be a nice idea to move 90337a7e8ccc26e25170c2ca353b7e25de8a6eef into separate PR and release it with #682 in v12.

#536 shouldn't have any breaking (non-deprecatable) change, including 90337a7e8ccc26e25170c2ca353b7e25de8a6eef. I will also remove 90337a7e8ccc26e25170c2ca353b7e25de8a6eef from #536 later.

### CODE REVIEW

**Review by kevinkjt2000 — CHANGES_REQUESTED** [review]
@PerchunPak An older file was moved because `enforces_secure_chat` is missing in attributes. 

@ItsDrike there is a DeprecationWarning; should it mention v12/v13 as a removal timeline?

**Comment by ItsDrike** [comment]
> there is a DeprecationWarning; should it mention v12/v13 as a removal timeline?

Oh yeah, how did I miss that? lol, guess I'm blind. Anyway, it depends on how fast do we want to postpone any pending breaking changes. If we do v12, it will block #682 until the end of the deprecation period here. Since the original deprecations in place used dates and not versions though, and that date there was 2023-11 (iirc), we should probably push a v12 now with those deprecations removed, as a breaking change, and have this deprecated until v13.

**Comment by PerchunPak** [comment]
> An older file was moved because enforces_secure_chat is missing in attributes.

Yeah, accidentally copied from the wrong branch. Will fix it quiet later.

> If we do v12, it will block #682 until the end of the deprecation period here

I would like to merge this together with #682 and release both PRs in v12, don't understand what blocks us from merging #682.

> at least as far as I'm aware, we don't actually have a versioning policy/guidelines page written out

I thought we just strictly follow https://semver.org.

**Comment by ItsDrike** [comment]
> I thought we just strictly follow https://semver.org/.

Semver doesn't contain anything about deprecations, it just mentions that breaking changes should be done as a major release. Is deprecation a breaking change though? That's what we should establish in the versioning guarantees (see the mcproto docs link).

> I would like to merge this together with https://github.com/py-mine/mcstatus/pull/682 and release both PRs in v12, don't understand what blocks us from merging https://github.com/py-mine/mcstatus/pull/682.

We can release both in v12, we just can't mark the deprecation period as "until v12", since I'd like to see at least 2 months there, and #682 is a breaking change, as it's removing a deprecation, so the code would actually end up broken, which forces us to make a major release once merged, i.e. we'd have to release v12. That's why these changes should be deprecated with a message saying "until v13", so in v13, the deprecations introduced here will be removed.

**Comment by PerchunPak** [comment]
Oh, yeah, I forgot that I mostly just blindly cherry-picked commit. Will fix it as well as other changes.

**Comment by PerchunPak** [comment]
Done. I also used `2024-3` instead of `v13`, as we everywhere else use dates instead of versions for deprecations.

**Review by ItsDrike — COMMENTED** [review]
Needs merge confict resolution, and the deprecation date should be bumped to at least 2024-05, or maybe even later

**Comment by ItsDrike** [comment]
I suppose this can be merged, though it'll definitely need bumping the deprecation dates. (Unless there is something else that this is waiting on, which I'm not aware of?)

**Pull request merged**
