### PR TITLE
Ignore socket failure to close during del

### PR DESCRIPTION
**Pull request by kevinkjt2000**
https://discord.com/channels/936788458939224094/938591600160956446/1010780929154875532

### CODE REVIEW

**Review by ItsDrike — APPROVED** [review]
Looks fine to me, although there is one detail I'd like to mention:

The commit here seems to have been made under a different git account (`ktindall@redhat.com`, instead of the annonymous github assigned email you usually commit under: `kevinkjt2000@users.noreply.github.com`). I assume you accidentally used your work email here, which has then also lead to the commit getting an "Unverified" status on github, since this git email doesn't seem to be associated with a registered github user. 

This isn't at all an issue that would prevent merging, however you might want to force-push and fix this. If you're fine with there being an unverified commit from this git account in the repo though, you can simply merge it, as functionality-wise it looks good.

**Review by PerchunPak — COMMENTED** [review]
Maybe move this try-ecept to `close` method instead of `__del__`?

**Comment by ItsDrike** [comment]
> Maybe move this try-ecept to `close` method instead of `__del__`?

I thought of that too, but I'm a believer of not silently suppressing errors, if the user called close explicitly, they should see it if the socket was closed already and if they're interested in suppressing that failure, they can handle it themselves in their try-except. This does make sense in `__del__` as the user may have explicitly called close, so we do want to handle for this, but I don't think it would actually make much sense to do so in `close` directly.

**Comment by PerchunPak** [comment]
Better would be at least document this error in `close` method.

**Comment by kevinkjt2000** [comment]
> Better would be at least document this error in close method.
I suspect that these errors won't happen under normal circumstances. Closing a socket ought to work. It is only during garbage collection calling `__del__` where behavior is exceptional and we know that it is safe to ignore.

**Pull request merged**
